$  ARCHIVO DE DATOS DEL PROGRAMA LOSA
$
Sistema No 1
$
$   NLOSA       FC        FY     ADICIONALES
$    [-]    [ton/cm2]  [ton/cm2]     [-]
      2       0.210      4.200        0
$
$    ID    TIPO    CARGA   ESPESOR     LX       LY       REC
$    [-]    [-]  [ton/m2]    [m]       [m]      [m]      [m]
      1     10     2.000    0.120     4.000    4.000    0.020
      2     21     2.000    0.120     4.000    5.000    0.020
$
$   ADIC. SEGUN X
         1
$
$      B-I        B-J      BALANCEO
         1         2         S
$
$   ADIC. SEGUN Y
         0
$
$  --- siguiente sistema ---
$
Cubierta techo
$
$   NLOSA       FC        FY     ADICIONALES
$    [-]    [ton/cm2]  [ton/cm2]     [-]
      1       0.210      4.200        1
$
$    ID    TIPO    CARGA   ESPESOR     LX       LY       REC
$    [-]    [-]  [ton/m2]    [m]       [m]      [m]      [m]
      1     50     1.500    0.150     6.000    6.000    0.025
$
$   ADIC. SEGUN X
         0
$
$   ADIC. SEGUN Y
         0
