$  ARCHIVO DE DATOS DEL PROGRAMA LOSA
$
Sistema No 1
$
$   NLOSA       FC        FY     ADICIONALES
$    [-]    [ton/cm2]  [ton/cm2]     [-]
      5       0.210      4.200        0
$
$    ID    TIPO    CARGA   ESPESOR     LX       LY       REC
$    [-]    [-]  [ton/m2]    [m]       [m]      [m]      [m]
      1     40     0.720    0.200     6.850    6.650    0.025
      2     40     0.720    0.200     6.850    6.650    0.025
      3     40     0.720    0.200     6.850    6.450    0.025
      4     40     0.720    0.200     6.850    6.450    0.025
      5     71     0.720    0.120    13.650    1.200    0.025
$
$   ADIC. SEGUN X
         2
$
$      B-I        B-J      BALANCEO
         1         2         S
         2         4         S
$
$   ADIC. SEGUN Y
         4
$
$      B-I        B-J      BALANCEO
         1         3         S
         2         4         S
         5         2         N
         5         1         N
