$  ARCHIVO DE DATOS DEL PROGRAMA LOSA
$
ADN TORRE PS2 S SEMISOTANO
$
$   NLOSA       FC        FY     ADICIONALES
$    [-]    [ton/cm2]  [ton/cm2]     [-]
      3       0.210      4.200        0
$
$    ID    TIPO    CARGA   ESPESOR     LX       LY       REC
$    [-]    [-]  [ton/m2]    [m]       [m]      [m]      [m]
      1     60     1.550    0.250     4.000    7.800    0.020
      2     52     1.470    0.250     7.200    7.800    0.020
      3     51     1.430    0.250     4.200    3.000    0.020
$
$   ADIC. SEGUN X
         1
$
$      B-I        B-J      BALANCEO
         1         2         S
$
$   ADIC. SEGUN Y
         1
$
$      B-I        B-J      BALANCEO
         1         3         S
